### PR TITLE
Fix confirmation dialog bug so it renders markdown content instead of plain text content

### LINKED ISSUE #25: Bits.ConfirmationDialog should render Slack markdown, not just plain text
According to Slack which I confirmed, the text property on confirmation dialog on buttons supports markdown, but Block Builder is only supporting plain text.

Slack documentation: https://api.slack.com/reference/block-kit/composition-objects#confirm

See: https://github.com/raycharius/slack-block-builder/blob/master/src/bits/confirmation-dialog.js#L130

### PR DESCRIPTION
**Pull request by zzullick**
Fixes #25 

Allow confirmation dialogs to render markdown content instead of just plain text content as per what Slack supports.

### CODE REVIEW

**Review by tsnieman — APPROVED** [review]

**Comment by raycharius** [comment]
Hi Zack, thanks for sending this over! Have you tested this with the client? About a month ago, I noticed that they had markdown in the `text` parameter there, but when I tried to change the type from `plain_text` to `mrkdwn` and actually threw in some markdown, it didn't render correctly in the app. 

You can also see that here with Slack's [Block Builder](https://app.slack.com/block-kit-builder/T03JD99F9#%7B%22blocks%22:%5B%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22Here%20is%20an%20example%20of%20markdown%20that%20is%20valid:%5Cn%5CnNot%20_really_%20sure%20*why*%20markdown%20here%20is%20is%20not%20working%20🙄%22%7D%7D,%7B%22type%22:%22divider%22%7D,%7B%22type%22:%22actions%22,%22elements%22:%5B%7B%22type%22:%22button%22,%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22But%20It%20Doesn't%22,%22emoji%22:true%7D,%22value%22:%22click_me_123%22,%22confirm%22:%7B%22title%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Are%20you%20sure?%22%7D,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22Not%20_really_%20sure%20*why*%20markdown%20here%20is%20is%20not%20working%20🙄%22%7D,%22confirm%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Do%20it%22%7D,%22deny%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Stop,%20I've%20changed%20my%20mind!%22%7D%7D%7D%5D%7D%5D%7D)

**Comment by zzullick** [comment]
> 
> 
> Hi Zack, thanks for sending this over! Have you tested this with the client? About a month ago, I noticed that they had markdown in the `text` parameter there, but when I tried to change the type from `plain_text` to `mrkdwn` and actually threw in some markdown, it didn't render correctly in the app.
> 

Hmm, that is interesting. I did test it in the client, but the case in our application we were testing was not for formatting but for channel links, which only work in markdown text objects and not plain text objects. It does properly work in this case and fix the issue I was having. Please see below, which renders literally as `<#{channelId}>` without this fix. I wonder why the behavior of these are so odd in the sense that they are inconsistent with other Slack markdown text objects?

image

**Comment by zzullick** [comment]
I happened to have a meeting with the Slack developer relations team so I went ahead and reported this behavior to them, as it is odd. That being said, since even though the markdown support of this construct is non-standard, this changes allows it to behave functionally in a way it is impossible to do without it (channel/user links) and the use of the text modifiers not working should be immediately obvious to the developer. Maybe even a note in the docs? What are your thoughts, @raycharius?

**Comment by raycharius** [comment]
Sounds good! I'll write up the change log and release it today/tomorrow. Thanks, Zack!

**Pull request merged**
